---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: astra, control center, bugs, known issues, problems 
summary: Problemas conhecidos identificam problemas que podem impedi-lo de usar esta versão do produto com sucesso. 
---
= Problemas conhecidos
:hardbreaks:
:allow-uri-read: 
:source-highlighter: highlight.js
:icons: font
:imagesdir: ../media/release-notes/


[role="lead"]
Problemas conhecidos identificam problemas que podem impedi-lo de usar esta versão do produto com sucesso.

Os seguintes problemas conhecidos afetam a versão atual:

* <<Backups e snapshots de aplicativos falharão se a volumesnapshotclass for adicionada após o gerenciamento de um cluster>>
* <<O gerenciamento de um cluster com Astra Control Center falha quando o arquivo kubeconfig contém mais de um contexto>>
* <<Um pod de monitoramento pode falhar em ambientes do Istio>>
* <<As operações de gerenciamento de dados da aplicação falham com erro de serviço interno (500) quando o Astra Trident está off-line>>
* <<As operações de restauração no local para as classes de storage de economia ONTAP nas falham>>
* <<A restauração a partir de um backup ao usar a criptografia em trânsito Kerberos pode falhar>>
* <<Os dados de backup permanecem no intervalo após a exclusão para buckets com política de retenção expirada>>




== Backups e snapshots de aplicativos falharão se a volumesnapshotclass for adicionada após o gerenciamento de um cluster

Backups e snapshots falham `UI 500 error` nesse cenário. Como solução alternativa, atualize a lista de aplicativos.



== O gerenciamento de um cluster com Astra Control Center falha quando o arquivo kubeconfig contém mais de um contexto

Você não pode usar um kubeconfig com mais de um cluster e contexto nele. Consulte link:https://kb.netapp.com/Cloud/Astra/Control/Managing_cluster_with_Astra_Control_Center_may_fail_when_using_default_kubeconfig_file_contains_more_than_one_context["artigo da base de conhecimento"^] para obter mais informações.



== Um pod de monitoramento pode falhar em ambientes do Istio

Se você emparelhar o Astra Control Center com o Cloud Insights em um ambiente Istio, o `telegraf-rs` pod poderá falhar. Como solução alternativa, execute as seguintes etapas:

. Encontre o pod avariado:
+
[listing]
----
kubectl -n netapp-monitoring get pod | grep Error
----
+
Você deve ver saída semelhante ao seguinte:

+
[listing]
----
NAME READY STATUS RESTARTS AGE
telegraf-rs-fhhrh 1/2 Error 2 (26s ago) 32s
----
. Reinicie o pod avariado, substituindo `<pod_name_from_output>` pelo nome do pod afetado:
+
[listing]
----
kubectl -n netapp-monitoring delete pod <pod_name_from_output>
----
+
Você deve ver saída semelhante ao seguinte:

+
[listing]
----
pod "telegraf-rs-fhhrh" deleted
----
. Verifique se o pod foi reiniciado e não está em um estado de erro:
+
[listing]
----
kubectl -n netapp-monitoring get pod
----
+
Você deve ver saída semelhante ao seguinte:

+
[listing]
----
NAME READY STATUS RESTARTS AGE
telegraf-rs-rrnsb 2/2 Running 0 11s
----




== As operações de gerenciamento de dados da aplicação falham com erro de serviço interno (500) quando o Astra Trident está off-line

Se o Astra Trident em um cluster de aplicações ficar offline (e for colocado novamente online) e se forem encontrados 500 erros de serviço interno ao tentar o gerenciamento de dados de aplicações, reinicie todos os nós do Kubernetes no cluster de aplicações para restaurar a funcionalidade.



== As operações de restauração no local para as classes de storage de economia ONTAP nas falham

Se você executar uma restauração no local de um aplicativo (restaurar o aplicativo para seu namespace original) e a classe de armazenamento do aplicativo usar o `ontap-nas-economy` driver, a operação de restauração poderá falhar se o diretório instantâneo não estiver oculto. Antes de restaurar no local, siga as instruções em link:../use/protect-apps.html#enable-backup-and-restore-for-ontap-nas-economy-operations["Habilite o backup e a restauração de operações de economia de ONTAP nas"^] para ocultar o diretório de instantâneos.



== A restauração a partir de um backup ao usar a criptografia em trânsito Kerberos pode falhar

Quando você restaura um aplicativo de um backup para um back-end de armazenamento que esteja usando a criptografia em trânsito Kerberos, a operação de restauração pode falhar. Esse problema não afeta a restauração de um snapshot ou a replicação dos dados do aplicativo usando o NetApp SnapMirror.


NOTE: Ao usar a criptografia em trânsito Kerberos com volumes NFSv4, verifique se os volumes NFSv4 estão usando as configurações corretas. Consulte a seção Configuração de domínio do NetApp NFSv4 (página 13) do https://www.netapp.com/media/16398-tr-3580.pdf["Guia de práticas recomendadas e aprimoramentos do NetApp NFSv4"^].



== Os dados de backup permanecem no intervalo após a exclusão para buckets com política de retenção expirada

Se você excluir o backup imutável de um aplicativo após a política de retenção do bucket expirar, o backup será excluído do Astra Control, mas não do bucket. Esse problema será corrigido em um lançamento futuro.



== Encontre mais informações

* link:../release-notes/known-limitations.html["Limitações conhecidas"]

